name: Release

on:
  push:
    tags:
      - v*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3
      - name: Release
        run: gh release create ${{ github.ref_name }}

